name:                json-parser
version:             0.1.0.0
github:              "phtb233/json-parser"
license:             BSD3
author:              "phtb233"
maintainer:          "stephen_621@msn.com"
copyright:           "2019 phtb233"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/phtb233/json-parser#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  json-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-parser

tests:
  json-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-parser
